In [1]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


# Numpy Array

- to perform mathmatical calculation on n dimentional data with efficiency and accuracy
- array is same as list which uses continue memory sequence for storing data of same data type
- n dimention(nd) array
- nd array is homogenious 
- nd array can be multidimention
- nd array can be of various DataType (e.g. int8 int16 float64)
- nd array support multiple methods
- nd array can be converted to different shape 

In [2]:
import numpy as np

In [19]:
d = [22,11,12,14,25]
print(d)
# [24,13,14,16,27]   
print(sum(d))
from functools import reduce
print(reduce(lambda a,b: a*b,d))
for index,data in enumerate(d) :
    d[index] = data+2
print(d)

[22, 11, 12, 14, 25]
84
1016400
[24, 13, 14, 16, 27]


<img src = "../images/standarddeviation.png">

In [ ]:
data1= [2,4,6,8,10,15]
print(np.std(data1),np.mean(data1),sep="\n")
data2 = [5,7,9,6,8,10]
print(np.std(data2),np.mean(data2),sep="\n")

4.232808366400098
7.5
1.707825127659933
7.5


In [ ]:
import numpy as np      # inbuild methods support
d = [22,11,12,14,25]
d = np.array(d)
print(d.sum())
print(d.prod())
print(d+2)
print(d.std())
print(d.mean())
print(d.var())
print(np.quantile(d,0.50))      # middle Value

84
1016400
[24 13 14 16 27]
5.635601121442148
16.8
31.76
14.0


In [40]:
data = np.array([1,2,3,4,5,6,7,8,9,10,11,12])
data.reshape(-1,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

## Broadcasting

In [ ]:
import numpy as np
d = np.array([1,2,3,4])  # applying on one dimensional array 
print(d)
print(d+2)
print(d*2)
print(d/2)
print(d//2)
print(d**2)

[1 2 3 4]
[3 4 5 6]
[2 4 6 8]
[0.5 1.  1.5 2. ]
[0 1 1 2]
[ 1  4  9 16]


In [ ]:
d = np.array(range(1,5)).reshape(2,2) 
print(d)
print(d*2) # applying on two dimensional array 

[[1 2]
 [3 4]]
[[2 4]
 [6 8]]


## Random value

In [31]:
np.random.seed(42)   # seed to freeze the random values
print(np.random.random(), end="\n\n")
print(np.random.random(3), end="\n\n")
print(np.random.random([2,2]), end="\n\n")

0.3745401188473625

[0.95071431 0.73199394 0.59865848]

[[0.15601864 0.15599452]
 [0.05808361 0.86617615]]



In [33]:
print(np.random.randint(1,100,20))       # 20 random int from 1 to 100(excluded)

[42 92 60 80 15 62 62 47 62 51 55 64  3 51  7 21 73 39 18  4]


In [9]:
np.random.randn(12).reshape(6,2)

array([[ 0.87310815,  0.57714986],
       [ 1.64041945, -0.25690743],
       [-0.8886164 ,  0.92990986],
       [ 0.07764771,  0.62043524],
       [ 1.17050561, -2.03229738],
       [ 0.77794296,  0.23865495]])

In [41]:
np.linspace(1,25,5)

array([ 1.,  7., 13., 19., 25.])

In [190]:
import random
random.sample([1,2,3,4,5,6],2,counts=[0,0,2,2,2,10])

[6, 6]

In [204]:
np.random.choice([1,2,3,4,5],2,p=[0,0,0.1,0.3,0.6])

array([4, 5])

In [ ]:
np.arange(1,100,11)    # similar to range

array([ 1, 12, 23, 34, 45, 56, 67, 78, 89])

In [217]:
data= np.array([[1,2,3,4],[5,6,7,8]])
print(data.ravel(),end="\n\n")
print(data)
print(data.flatten())


[1 2 3 4 5 6 7 8]

[[1 2 3 4]
 [5 6 7 8]]
[1 2 3 4 5 6 7 8]


In [218]:
a = np.array([[1,2],[3,4]])
b = np.array([2,3])
a*b

array([[ 2,  6],
       [ 6, 12]])

In [221]:
a = np.array([[1,2],[3,4]])
b = np.array([2,3])
print(a.dot(b))
print(b.dot(a))

[ 8 18]
[11 16]


In [ ]:
b = np.array([2,3])
a = np.array([[1,2],
              [3,4]])

In [2]:
import numpy as np

In [2]:
a = np.array([[1,2],
              [3,4]])
a

array([[1, 2],
       [3, 4]])

In [3]:
np.matrix_transpose(a)

array([[1, 3],
       [2, 4]])

In [6]:
np.ones((2,4))
np.zeros((2,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [11]:
d = np.array([[1,2,3],[4,3,2]])
d

array([[1, 2, 3],
       [4, 3, 2]])

In [15]:
np.identity(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [ ]:
np.sin(30 * np.pi / 180)

In [19]:
print(np.sin(30))
np.cos(10)
np.cos(10)

-0.9880316240928618


np.float64(-0.8390715290764524)

In [22]:
np.sqrt(4)

np.float64(2.0)

In [29]:
16 ** 0.25

2.0

In [37]:
np.e

2.718281828459045

In [36]:
np.e ** 2.772588722239781

15.999999999999996

In [34]:
np.log(16)

np.float64(2.772588722239781)

In [31]:
np.log10(100)

np.float64(2.0)

In [6]:
np.hstack([[1,2,3,4],[5,6,7,8],[2,3,4]])

array([1, 2, 3, 4, 5, 6, 7, 8, 2, 3, 4])

In [9]:
a =[1,2,3,4]
b = [5,6,7,8]
np.vstack([a,b,[2,3,4,3]])

array([[1, 2, 3, 4],
       [5, 6, 7, 8],
       [2, 3, 4, 3]])

In [15]:
np.split([1,2,3,4,5,6],[3,5])

[array([1, 2, 3]), array([4, 5]), array([6])]